//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notary2015
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class license
    {
        public int idLicense { get; set; }
        public Nullable<int> Nomber { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public int Notary_idNotary { get; set; }
    
        [JsonIgnore]
        public virtual notary notary { get; set; }
    }
}
