//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notary2015
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class notarysEntities : DbContext
    {
        public notarysEntities()
            : base("name=notarysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<district> districts { get; set; }
        public DbSet<furlought> furloughts { get; set; }
        public DbSet<license> licenses { get; set; }
        public DbSet<notary> notaries { get; set; }
        public DbSet<office> offices { get; set; }
        public DbSet<order> orders { get; set; }
    }
}
