//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notary2015
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class notary
    {
        public notary()
        {
            this.furloughts = new HashSet<furlought>();
            this.licenses = new HashSet<license>();
            this.orders = new HashSet<order>();
        }
    
        public int idNotary { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> Certificate { get; set; }
        public Nullable<System.DateTime> Suspension { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> Office_idOffice { get; set; }
        public int District_idDistrict { get; set; }
        
        [JsonIgnore]
        public virtual district district { get; set; }
        [JsonIgnore]
        public virtual office office { get; set; }
        [JsonIgnore]
        public virtual ICollection<furlought> furloughts { get; set; }
        [JsonIgnore]
        public virtual ICollection<license> licenses { get; set; }
        [JsonIgnore]
        public virtual ICollection<order> orders { get; set; }
    }
}
