//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notary2015
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class office
    {
        public office()
        {
            this.notaries = new HashSet<notary>();
        }
    
        public int idOffice { get; set; }
        public string Office_Title { get; set; }
        public Nullable<System.DateTime> Foundation { get; set; }
        public Nullable<System.DateTime> Status { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }

        [JsonIgnore]
        public virtual ICollection<notary> notaries { get; set; }
    }
}
